LalitKumar/index.html, LalitKumar/style.css
Created a simple table using HTML and styled using CSS
Issue resolved #1
=> Biodata Table added

subhangi/index.html, subhangi/style.css
I have created a new folder in which I have added a navbar in the index.html file.
=> Add this to your code: Navbar added

mihir/contact-us.html, mihir/styles.css
=> issue no 13 resolved

Shubhrajyoti/contact.html, Shubhrajyoti/style.css
=> Issue no.13 resolved:create a contact us section

mihir 1/index.html
=> issue no 2 resolved

Aashu-f/Aastha Mohanty/index.html, Aashu-f/Aastha Mohanty/style.css
In this issue  I have changed the form position and made few css changes.
=> changed form position and made few css changes.

Amit Kumar Satapathy/index4.html
=> ISSUE #5 SOLVED

Soumya Sagar/issue 2 solved/index.html, Soumya Sagar/issue 2 solved/styles.css
=> added login form

Avipsha Mishra/index3.html, Avipsha Mishra/style.css
=> #13 issue solved

Priti_Priyadarsini/index.html, Priti_Priyadarsini/style.css
Issue Addressed #4 
Using flexbox centred an image with width 50% and added refreshing images using random image generator.
=> Issue #4 Resolved

Shradha M/.vscode/settings.json, Shradha M/INDEX.HTML, Shradha M/STYLE.CSS, shradha/index.html, shradha/style.css
=> login form

Abhishek/contact.html
#13 Added minimalistic Contact us section
=>  Added minimalistic Contact us section

Avipsha Mishra/index4.html, Avipsha Mishra/style2.css
=> issue #2 solved

RahulSinghGurjar/app.js, RahulSinghGurjar/login.html, RahulSinghGurjar/style1.css
Hey please merge this pull request to your repository.
=> Issue no. 2 resolved 

Button_CSS_Generator/index.html, Button_CSS_Generator/script.js, Button_CSS_Generator/style.css
Added a simple Button CSS Generator, using HTML, CSS, JS. #175
=> Added a Button_CSS_Generator

Omkar Mandal/issue11.css, Omkar Mandal/issue11.html
Issue #1 Resolved. Created A biodata using HTML Table and CSS. Kindly Review
=> Issue 1 Resolved Kindly Review

Rajsekhar Pradhan/Simple Login Page Using HTML and CSS/index.html, Rajsekhar Pradhan/Simple Login Page Using HTML and CSS/style.css
=> Simple Login Page Using HTML and CSS

Rajsekhar Pradhan/Centering an image without using flexbox/index.html
=> Centering an image without using flexbox

Tusar Contact us/index.html, Tusar Contact us/style.css, Tusar ID Card/index.html, Tusar ID Card/style.css
=> issue #13 resolved

Sajal/ContactPage/index.html, Sajal/ContactPage/styles.css, Sajal/Navbar/index.html, Sajal/Navbar/styles.css
Made a responsive contact page with HTML and CSS
=> Contact Page Issue#13

Gopal Jain/Centering an image using flexbox/index.html
=> Centering an image using flexbox

index.html
there was missing a closing div
=> Add missing </div>

Priyadarshni_12/index.html, Priyadarshni_12/script.js, Priyadarshni_12/style.css
Added a new  frontend project named guesser game
=> Added a  gusser game

Tusar Payment Gateway/index.html, Tusar Payment Gateway/index.js, Tusar Payment Gateway/style.css
=> issue #115 resolved

Sajal_ImageWithFlexbox/index.html, Sajal_ImageWithFlexbox/styles.css
=>  Resolved Issue#4

Sajal_N/index.html, Sajal_N/styles.css
Added a navbar in a new folder solving the issue 12
=> Added Navbar Issue #12

Button Animations/index.html, Button Animations/style.css
The previous PR #269  was for contact us section (issue #13 ). This is for issue #180
=> Social Button Animation

mihir3/index.html, mihir3/style.css
=> issue no 1 reseolved

shar-covid_website/index.html, shar-covid_website/style.css
Made a covid awareness website using html and css
=> Created Covid Awareness Website

Akhil-login_form/index.html, Akhil-login_form/style.css
Hey @IshitaSatpathy     
Akhil-login_form-added
Please review my pr
=> #2 issue resolved

Akhil-contact_us/index.html
hey @IshitaSatpathy contact-us form added
please review my pr
=> #13 issue resolved
